int main () {

#if defined(MINI_ICONS)
SetMessageMask (Fvwm_fd, (M_CONFIGURE_WINDOW | M_RES_CLASS | M_RES_NAME | M_ADD_WINDOW | M_DESTROY_WINDOW | M_ICON_NAME | M_DEICONIFY | M_ICONIFY | M_ICON_LOCATION | M_END_WINDOWLIST | M_NEW_DESK | M_NEW_PAGE | M_FOCUS_CHANGE | M_WINDOW_NAME | M_CONFIG_INFO | M_MINI_ICON | M_STRING));
#endif

#if !defined(MINI_ICONS)
SetMessageMask (Fvwm_fd, (M_CONFIGURE_WINDOW | M_RES_CLASS | M_RES_NAME | M_ADD_WINDOW | M_DESTROY_WINDOW | M_ICON_NAME | M_DEICONIFY | M_ICONIFY | M_ICON_LOCATION | M_END_WINDOWLIST | M_NEW_DESK | M_NEW_PAGE | M_FOCUS_CHANGE | M_WINDOW_NAME | M_CONFIG_INFO | M_STRING));
#endif

}
