int main (){

	SetMessageMask(Fvwm_fd,M_ADD_WINDOW | M_CONFIGURE_WINDOW | M_DESTROY_WINDOW | M_WINDOW_NAME | M_ICON_NAME | M_RES_NAME | M_DEICONIFY |  M_ICONIFY | M_END_WINDOWLIST | M_FOCUS_CHANGE | M_CONFIG_INFO | M_END_CONFIG_INFO | M_NEW_DESK | M_SENDCONFIG
	#ifdef MINI_ICONS
			 | M_MINI_ICON
	#endif
			);


}
